---
title: "Memória de operações - planilha PAP e PDT"
author: "João Pedro Magro"
date: "Última atualização no dia `r format(Sys.time(), '%d de %B de %Y')`"
output: html_document
---

# BIBLIOTECAS

```{r bibliotecas , echo=TRUE}
#'*Bilbliotecas*
library(tidyverse)
library(readxl)
library(xlsx)
```

# FUNÇÃO PLANILHEIRO

```{r PLANIHLEIRO, echo=TRUE}
PLANILHEIRO<-function(DF,VARS,NOME){
   TESTE<-tibble(A=c("TESTE"),B=c("TESTE"))
   write.xlsx(as.data.frame(TESTE), file = paste(NOME,"xlsx",sep="."), sheetName = "RUMB")
   for (VAR in VARS) {
     DIN<-DF%>%filter(VARIAVEIS==VAR)%>%select(2:19)
      write.xlsx(as.data.frame(DIN), file = paste(NOME,"xlsx",sep="."), sheetName = print(VAR), append = TRUE)
      
   }
}

```

# DADOS

```{r DADOS, echo=TRUE}
BD_COMP_PAP_PTD_ST_DEFLA_ANA_W <- readRDS("~/R_CORE/GitHub/IAIABR/PAP_PTD/PAP_PTD_DADOS/BD_COMP_PAP_PTD_ST_DEFLA_ANA_W.rds")
BD_COMP_PAP_PTD_ST_DEFLA_ANA_L<-pivot_longer(BD_COMP_PAP_PTD_ST_DEFLA_ANA_W,
                                             names_to = "VARIAVEIS",
                                             values_to = "VALORES",
                                             cols = c(3:8))
BD_COMP_PAP_PTD_ST_DEFLA_ANA_L<-BD_COMP_PAP_PTD_ST_DEFLA_ANA_L%>%
   select(VARIAVEIS,ANO,VALORES,PRODUTO)
BD_COMP_PAP_PTD_ST_DEFLA_ANA_W<-pivot_wider(BD_COMP_PAP_PTD_ST_DEFLA_ANA_L,
                                             id_cols = c(VARIAVEIS,ANO),
                                            names_from = PRODUTO,
                                            values_from = VALORES)
```


```{r OPERAÇÃO, echo=TRUE}
HABBA<-unique(BD_COMP_PAP_PTD_ST_DEFLA_ANA_L$VARIAVEIS)

PLANILHEIRO(BD_COMP_PAP_PTD_ST_DEFLA_ANA_W,HABBA,"PAP_PTD")
```